server:
  port: 8015

###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=testdb
    username: test
    password: test
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
